name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Update Stats
        uses: ./
        with:
          github-stats-token: ${{ secrets.STATS_TOKEN }}
          google-application-credentials: ${{ secrets.GOODLE_APPLICATION_CREDENTIALS }}
          spreadsheet-id: ${{ secrets.SPREADSHEET_ID }}
          github-owner-name: introlab
          github-project-name: github-stats-action